import { useMemo } from 'react';

export const useSlidesData = () => {
  const slidesData = useMemo(() => ({
    slides: [
      {
        id: 1,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 1",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "SAP Analytics Cloud",
          title: "Step 1",
          description: "Please check if the SuccessFactors mobile application is available in your work profile. Else, Open 'Company portal' in your mobile device.",
          buttonText: "Get Started",
          image: "/image3.png",
          icon: "bar-chart-3",
          gradient: "from-blue-600 via-blue-700 to-indigo-800",
        },
      },
      {
        id: 2,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 2",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Smart Visualization",
          title: "Step 2",
          description: "Click on the 'Menu' icon.",
          buttonText: "Explore Templates",
          image: "/image4.png",
          icon: "bar-chart-3",
          gradient: "from-emerald-500 via-teal-600 to-cyan-700",
        },
      },
      {
        id: 3,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 3",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Enterprise Planning",
          title: "Step 3",
          description: "Click on 'Get Apps' option. ",
          buttonText: "Start Planning",
          image: "/image5.png",
          icon: "users",
          gradient: "from-purple-600 via-violet-700 to-indigo-800",
        },
      },
      {
        id: 4,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 4",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Smart Predict",
          title: "Step 4",
          description: "Search for 'SAP SuccessFactors Mobile' application and click on install.",
          buttonText: "Try Predictions",
          image: "/image6.png",
          icon: "zap",
          gradient: "from-red-500 via-pink-600 to-purple-700",
        },
      },
      {
        id: 5,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 5",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 5",
          description: "Open the installed SAP SuccessFactors Mobile app and you will be directly logged in without credentials.",
          buttonText: "Configure Security",
          image: "/image7.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 6,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 6",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image8.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 7,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 1",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "SAP Analytics Cloud",
          title: "Step 1",
          description: "Please check if the SuccessFactors mobile application is available in your work profile. Else, Open 'Company portal' in your mobile device.",
          buttonText: "Get Started",
          image: "/image9.png",
          icon: "bar-chart-3",
          gradient: "from-blue-600 via-blue-700 to-indigo-800",
        },
      },
      {
        id: 8,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 2",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Smart Visualization",
          title: "Step 2",
          description: "Click on the 'Menu' icon.",
          buttonText: "Explore Templates",
          image: "/image10.png",
          icon: "bar-chart-3",
          gradient: "from-emerald-500 via-teal-600 to-cyan-700",
        },
      },
      {
        id: 9,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 3",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Enterprise Planning",
          title: "Step 3",
          description: "Click on 'Get Apps' option. ",
          buttonText: "Start Planning",
          image: "/image11.png",
          icon: "users",
          gradient: "from-purple-600 via-violet-700 to-indigo-800",
        },
      },
      {
        id: 10,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 4",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Smart Predict",
          title: "Step 4",
          description: "Search for 'SAP SuccessFactors Mobile' application and click on install.",
          buttonText: "Try Predictions",
          image: "/image12.png",
          icon: "zap",
          gradient: "from-red-500 via-pink-600 to-purple-700",
        },
      },
      {
        id: 11,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 5",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Steo 5",
          description: "Open the installed SAP SuccessFactors Mobile app and you will be directly logged in without credentials.",
          buttonText: "Configure Security",
          image: "/image13.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 12,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 6",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image14.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 13,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Step 7",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image15.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 14,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Step 7",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "After finishing the previous step, you'll be taken to the SuccessFactors app screen as shown below.",
          buttonText: "Configure Security",
          image: "/image16.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
    
      
    ],
  }), []);

  const homePageData = useMemo(() => ({
    header: "Start Your Journey",
    tabs: [
      {
        title: "SuccessFactor App Installation",
        description: "Success Factors app at TATA Consumer Products enables seamless HR access and employee self-service on Android with secure login and smooth navigation.",
        image: "image1.png",
        buttonText: "Demo Installation",
        color: "blue",
        icon: "globe",
        type: "Installation",
      },
      {
        title: "Template Gallery",
        description: "Browse pre-built dashboards and reports designed for your industry and business function",
        image: "image2.jpg",
        buttonText: "Browse Gallery",
        color: "emerald",
        icon: "bar-chart-3",
        type: "Gallery",
      },
      {
        title: "Learning Center",
        description: "Access tutorials, best practices, and certification programs to master SAP Analytics",
        image: "image1.png",
        buttonText: "Start Learning",
        color: "purple",
        icon: "users",
        type: "Learning",
      },
    ],
  }), []);

  return { slides: slidesData.slides, homePageData };
};