import { useMemo } from 'react';

export const useSlidesData = () => {
  const slidesData = useMemo(() => ({
    slides: [
      {
        id: 1,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "SAP Analytics Cloud",
          title: "Step 1",
          description: "Please check if the SuccessFactors mobile application is available in your work profile. Else, Open 'Company portal' in your mobile device.",
          buttonText: "Get Started",
          image: "/image3.png",
          icon: "bar-chart-3",
          gradient: "from-blue-600 via-blue-700 to-indigo-800",
        },
      },
      {
        id: 2,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Smart Visualization",
          title: "Step 2",
          description: "Click on the 'Menu' icon.",
          buttonText: "Explore Templates",
          image: "/image4.png",
          icon: "bar-chart-3",
          gradient: "from-emerald-500 via-teal-600 to-cyan-700",
        },
      },
      {
        id: 3,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Enterprise Planning",
          title: "Step 3",
          description: "Click on 'Get Apps' option. ",
          buttonText: "Start Planning",
          image: "/image5.png",
          icon: "users",
          gradient: "from-purple-600 via-violet-700 to-indigo-800",
        },
      },
      {
        id: 4,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Smart Predict",
          title: "Step 4",
          description: "Search for 'SAP SuccessFactors Mobile' application and click on install.",
          buttonText: "Try Predictions",
          image: "/image6.png",
          icon: "zap",
          gradient: "from-red-500 via-pink-600 to-purple-700",
        },
      },
      {
        id: 5,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 5",
          description: "Open the installed SAP SuccessFactors Mobile app and you will be directly logged in without credentials.",
          buttonText: "Configure Security",
          image: "/image7.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 6,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image8.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 7,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "SAP Analytics Cloud",
          title: "Step 1",
          description: "Please check if the SuccessFactors mobile application is available in your work profile. Else, Open 'Company portal' in your mobile device.",
          buttonText: "Get Started",
          image: "/image9.png",
          icon: "bar-chart-3",
          gradient: "from-blue-600 via-blue-700 to-indigo-800",
        },
      },
      {
        id: 8,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Smart Visualization",
          title: "Step 2",
          description: "Click on the 'Menu' icon.",
          buttonText: "Explore Templates",
          image: "/image10.png",
          icon: "bar-chart-3",
          gradient: "from-emerald-500 via-teal-600 to-cyan-700",
        },
      },
      {
        id: 9,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Enterprise Planning",
          title: "Step 3",
          description: "Click on 'Get Apps' option. ",
          buttonText: "Start Planning",
          image: "/image11.png",
          icon: "users",
          gradient: "from-purple-600 via-violet-700 to-indigo-800",
        },
      },
      {
        id: 10,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Smart Predict",
          title: "Step 4",
          description: "Search for 'SAP SuccessFactors Mobile' application and click on install.",
          buttonText: "Try Predictions",
          image: "/image12.png",
          icon: "zap",
          gradient: "from-red-500 via-pink-600 to-purple-700",
        },
      },
      {
        id: 11,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Steo 5",
          description: "Open the installed SAP SuccessFactors Mobile app and you will be directly logged in without credentials.",
          buttonText: "Configure Security",
          image: "/image13.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 12,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image14.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 13,
        title: "Welcome to SAP SuccessFactors app installation on ios",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on ios devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"ios",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "Choose any options for sending Notifications.",
          buttonText: "Configure Security",
          image: "/image15.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 14,
        title: "Welcome to SAP SuccessFactors app installation on android",
        subtitle: "Configured and tested the SAP SuccessFactors app installation on Android devices to ensure secure login, smooth setup, and optimal user access.",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "After finishing the previous step, you'll be taken to the SuccessFactors app screen as shown below.",
          buttonText: "Configure Security",
          image: "/image16.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 15,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 1",
          description: "Open the app and click on SSO login.",
          buttonText: "Configure Security",
          image: "/image17.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 16,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 2",
          description: "Please enter your tata consumer email address and click next",
          buttonText: "Configure Security",
          image: "/image18.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 17,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 3",
          description: "It will redirect to Microsoft edge browser, once you reach the page, please Select your tata consumer email address",
          buttonText: "Configure Security",
          image: "/image19.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 18,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 4",
          description: "Click continue",
          buttonText: "Configure Security",
          image: "/image20.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 19,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 5",
          description: "If Bluetooth is off on your device, please turn it on. Bluetooth is required to use the app.",
          buttonText: "Configure Security",
          image: "/image21.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 20,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Click on Allow",
          buttonText: "Configure Security",
          image: "/image22.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 21,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"installation",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "If your Phone support NFC, please enable the NFC.",
          buttonText: "Configure Security",
          image: "/image23.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 22,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 8",
          description: "Enable NFC on Phone Settings.",
          buttonText: "Configure Security",
          image: "/image24.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 23,
        title: "Welcome to Spintly door access app installation on android",
        subtitle: "Spintly mobile door access applications will be pushed on Android devices Open the app from your work profile",
        type: "feature",
        osType:"android",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 9",
          description: "Now, site details will be listed as below. Click on the drop-down menu on site information.",
          buttonText: "Configure Security",
          image: "/image25.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 24,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 1",
          description: "Spintly mobile door access application will be pushed on ios devices and below notification will appear.",
          buttonText: "Configure Security",
          image: "/image26.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 25,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 2",
          description: "Open the app and click Allow.",
          buttonText: "Configure Security",
          image: "/image27.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 26,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 3",
          description: "Click on SSO Login.",
          buttonText: "Configure Security",
          image: "/image28.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 27,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 4",
          description: "Please enter your tata consumer email address and click next.",
          buttonText: "Configure Security",
          image: "/image29.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 28,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 5",
          description: "Click on continue.",
          buttonText: "Configure Security",
          image: "/image30.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 29,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 6",
          description: "Select your tata consumer email address.",
          buttonText: "Configure Security",
          image: "/image31.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 30,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 7",
          description: "Click continue.",
          buttonText: "Configure Security",
          image: "/image32.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 31,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 8",
          description: "Click “Allow while using app” and click continue.",
          buttonText: "Configure Security",
          image: "/image33.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 32,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 9",
          description: "Click “Allow while using app” and click continue.",
          buttonText: "Configure Security",
          image: "/image34.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 33,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 10",
          description: "Click on Allow.",
          buttonText: "Configure Security",
          image: "/image35.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 34,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 11",
          description: "To unlock door without opening the app, please select Always in locations.",
          buttonText: "Configure Security",
          image: "/image36.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 35,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 12",
          description: "Click on location and change from while using.",
          buttonText: "Configure Security",
          image: "/image37.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 36,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 13",
          description: "And choose as always.",
          buttonText: "Configure Security",
          image: "/image38.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-80Spintly door access0 to-zinc-900",
        },
      },
      {
        id: 37,
        title: "Welcome to Spintly door access app installation on ios",
        subtitle: "Spintly mobile door access applications will be pushed on ios devices Open the app from your work profile",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 14",
          description: "Now, site details will be listed as below. Click on the drop-down menu on site information.",
          buttonText: "Configure Security",
          image: "/image39.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
      {
        id: 38,
        title: "Welcome to MDM Enrolment Instructions for iPhone",
        subtitle: "Before enrolling the MDM on an iPhone, please check if the stolen device protection is enabled. If it is, follow the steps below",
        type: "feature",
        osType:"ios",
        homePageData:"Spintly",
        content: {
          header: "Data Protection",
          title: "Step 14",
          description: "Now, site details will be listed as below. Click on the drop-down menu on site information.",
          buttonText: "Configure Security",
          image: "/image39.png",
          icon: "shield",
          gradient: "from-gray-700 via-slate-800 to-zinc-900",
        },
      },
    
      
    ],
  }), []);

  const homePageData = useMemo(() => ({
    header: "Start Your Journey",
    tabs: [
      {
        title: "SuccessFactor App Installation",
        description: "Success Factors app at TATA Consumer Products enables seamless HR access and employee self-service on Android with secure login and smooth navigation.",
        image: "image1.png",
        buttonText: "Get Start",
        color: "blue",
        icon: "globe",
        type: "Installation",
      },
      {
        title: "Spintly Door Access",
        description: "Worked on the Mobile Door Access installation and configuration for iOS devices, ensuring smooth setup, secure connectivity, and seamless access control integration.",
        image: "image2.png",
        buttonText: "Get Start",
        color: "emerald",
        icon: "bar-chart-3",
        type: "Spintly",
      },
      {
        title: "Learning Center",
        description: "Access tutorials, best practices, and certification programs to master SAP Analytics",
        image: "image1.png",
        buttonText: "Get Start",
        color: "purple",
        icon: "users",
        type: "Learning",
      },
    ],
  }), []);

  return { slides: slidesData.slides, homePageData };
};